this addAction ["Request Green Jackal [GMG]","Scripts\request\veh_req_gjackgmg.sqf"];
this addAction ["Request Sand Jackal [GMG]","Scripts\request\veh_req_sjackgmg.sqf"];
this addAction ["Request Green Jackal [HMG]","Scripts\request\veh_req_gjackhmg.sqf"];
this addAction ["Request Sand Jackal [HMG]","Scripts\request\veh_req_sjackhmg.sqf"];
this addAction ["Request Green LR [Snatch]","Scripts\request\veh_req_gsnatch.sqf"];
this addAction ["Request Sand LR [Snatch]","Scripts\request\veh_req_ssnatch.sqf"];
this addAction ["Request Green WMIK [HMG]","Scripts\request\veh_req_gwmikhmg.sqf"];
this addAction ["Request Sand WMIK [HMG]","Scripts\request\veh_req_swmikhmg.sqf"];
this addAction ["Request Green WMIK [MILAN]","Scripts\request\veh_req_gwmikmilan.sqf"];
this addAction ["Request Sand WMIK [MILAN]","Scripts\request\veh_req_swmikmilan.sqf"];
this addAction ["Request Green HX60 [Transport]","Scripts\request\veh_req_ghx60.sqf"];
this addAction ["Request Sand HX60 [Transport]","Scripts\request\veh_req_shx60.sqf"];
this addAction ["Request Green Panther [GPMG]","Scripts\request\veh_req_gpanther.sqf"];
this addAction ["Request Sand Panther [GPMG]","Scripts\request\veh_req_spanther.sqf"];
this addAction ["Request Green Husky Logi [HMG]","Scripts\request\veh_req_ghusky.sqf"];
this addAction ["Request Sand Husky Logi [HMG]","Scripts\request\veh_req_shusky.sqf"];
this addAction ["Request Green LR [Ambulance]","Scripts\request\veh_req_gambo.sqf"];
this addAction ["Request Sand LR [Ambulance]","Scripts\request\veh_req_sambo.sqf"];
this addAction ["Request Green Bulldog [GMPG]","Scripts\request\veh_req_gbull.sqf"];
this addAction ["Request Sand Bulldog [GPMG]","Scripts\request\veh_req_sbull.sqf"];
this addAction ["Request Quadbike","Scripts\request\veh_req_quad.sqf"];
this addAction ["Request Motorbike","Scripts\request\veh_req_bike.sqf"];
this addAction ["Request Green HX58 [Fuel]","Scripts\request\veh_req_ghx58f.sqf"];
this addAction ["Request Green HX58 [Repair]","Scripts\request\veh_req_ghx58r.sqf"];
this addAction ["Request Sand HX58 [Fuel]","Scripts\request\veh_req_shx58f.sqf"];
this addAction ["Request Sand HX58 [Repair]","Scripts\request\veh_req_shx58r.sqf"]